/* =========================================================
   PROJECT: Vendor & Brand Performance Analysis
   DATABASE: PostgreSQL
   PURPOSE:
   - Analyze Purchases, Sales, Pricing & Freight
   - Build a consolidated vendor performance table
   ========================================================= */


-- =========================================================
-- 1️⃣ DATA UNDERSTANDING
-- Quick look at all base tables
-- =========================================================
SELECT * FROM begin_inventory;
SELECT * FROM end_inventory;
SELECT * FROM purchase_prices;
SELECT * FROM purchases;
SELECT * FROM sales;
SELECT * FROM vendor_invoice;



-- =========================================================
-- 2️⃣ VENDOR PURCHASE ANALYSIS
-- Business Question:
-- How much quantity & dollar value are we purchasing
-- from a vendor 4466?
-- =========================================================
SELECT
    brand,
    purchaseprice,
    SUM(quantity) AS total_purchase_quantity,
    SUM(dollars) AS total_purchase_dollars
FROM purchases
WHERE vendornumber = 4466
GROUP BY brand, purchaseprice;



-- =========================================================
-- 3️⃣ VENDOR SALES PERFORMANCE
-- Business Question:
-- How much sales is generated by this vendor's products?
-- =========================================================
SELECT
    brand,
    SUM(salesquantity) AS total_sales_quantity,
    SUM(salesprice) AS total_sales_price,
    SUM(salesdollars) AS total_sales_dollars
FROM sales
WHERE vendorno = 4466
GROUP BY brand;



-- =========================================================
-- 4️⃣ FREIGHT COST ANALYSIS
-- Business Question:
-- What is the total logistics cost per vendor?
-- =========================================================
SELECT
    vendornumber,
    SUM(freight) AS total_freight_cost
FROM vendor_invoice
GROUP BY vendornumber
ORDER BY vendornumber;



-- =========================================================
-- 5️⃣ UNIQUE PURCHASE ORDERS
-- Business Question:
-- How many unique POs are generated?
-- =========================================================
SELECT COUNT(DISTINCT ponumber) AS unique_po_count
FROM vendor_invoice;



-- =========================================================
-- 6️⃣ PURCHASE PRICE vs ACTUAL PRICE COMPARISON
-- Business Question:
-- Are we buying at the correct price?
-- =========================================================
SELECT
    p.vendornumber,
    p.vendorname,
    p.brand,
    p.purchaseprice,
    pp.price AS actual_price,
    SUM(p.quantity) AS total_quantity,
    SUM(p.dollars) AS total_dollars
FROM purchases p
JOIN purchase_prices pp
    ON p.vendornumber = pp.vendornumber
GROUP BY
    p.vendornumber, p.vendorname, p.brand,
    p.purchaseprice, pp.price;



-- =========================================================
-- 7️⃣ BRAND LEVEL SALES PERFORMANCE
-- =========================================================
SELECT
    brand,
    vendorno,
    SUM(salesquantity) AS total_sales_quantity,
    SUM(salesprice) AS total_sales_price,
    SUM(salesdollars) AS total_sales_dollars,
    SUM(excisetax) AS total_excise_tax
FROM sales
GROUP BY brand, vendorno
ORDER BY total_sales_dollars DESC;



-- =========================================================
-- 8️⃣ FINAL CONSOLIDATED BUSINESS VIEW (OPTIMIZED USING CTE)
-- PURPOSE:
-- Create a single view for:
-- Purchases + Sales + Freight + Pricing
-- =========================================================

WITH freight_summary AS (
    SELECT
        vendornumber,
        SUM(freight) AS total_freight_cost
    FROM vendor_invoice
    GROUP BY vendornumber
),

purchase_summary AS (
    SELECT
        vendornumber,
        vendorname,
        brand,
        description,
        purchaseprice,
        SUM(quantity) AS total_purchase_quantity,
        SUM(dollars) AS total_purchase_dollars
    FROM purchases
    GROUP BY 1,2,3,4,5
),

sales_summary AS (
    SELECT
        vendorno AS vendornumber,
        brand,
        SUM(salesquantity) AS total_sales_quantity,
        SUM(salesdollars) AS total_sales_dollars,
        SUM(salesprice) AS total_sales_price,
        SUM(excisetax) AS total_excise_tax
    FROM sales
    GROUP BY vendorno, brand
),

price_summary AS (
    SELECT
        vendornumber,
        brand,
        price AS actual_price,
        volume
    FROM purchase_prices
    GROUP BY 1,2,3,4
)

SELECT
    ps.vendornumber,
    ps.vendorname,
    ps.brand,
    ps.description,
    ps.purchaseprice,
    prs.actual_price,
    prs.volume,
    ps.total_purchase_quantity,
    ps.total_purchase_dollars,
    ss.total_sales_quantity,
    ss.total_sales_dollars,
    ss.total_sales_price,
    ss.total_excise_tax,
    fs.total_freight_cost
FROM purchase_summary ps
LEFT JOIN sales_summary ss
    ON ps.vendornumber = ss.vendornumber
    AND ps.brand = ss.brand
LEFT JOIN freight_summary fs
    ON ps.vendornumber = fs.vendornumber
LEFT JOIN price_summary prs
    ON ps.vendornumber = prs.vendornumber
ORDER BY ps.total_purchase_dollars DESC;



-- =========================================================
-- 9️⃣ CREATE FINAL ANALYTICS TABLE
-- This table will be used for dashboard / further analysis
-- =========================================================
CREATE TABLE vendor_sales_summary AS
SELECT * FROM (
    -- same final CTE query
) final;